version: '3.8'
services:
  app:
    build: .
    container_name: collabtask_app
    env_file: .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/collabtask
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    container_name: collabtask_mongo
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_DATABASE: collabtask
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  mongo-init-replica:
    image: mongo:7
    depends_on:
      - mongo
    entrypoint: ["sh", "-c", "sleep 5 && mongosh --host mongo:27017 --eval 'rs.initiate({_id:\"rs0\",members:[{_id:0,host:\"mongo:27017\"}]})' || true"]
    restart: "on-failure"
  mongo-express:
    image: mongo-express:1.0.2-18-alpine3.19
    container_name: collabtask_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    ports:
      - "8081:8081"
volumes:
  mongo_data:
