version: '3.8'

# Portainer Server Setup für komplettes Docker-Management
# Zugriff: https://217.154.223.78:9443 (HTTPS)
# Backup: http://217.154.223.78:9000 (HTTP)

services:
  # Portainer CE (Community Edition)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_server
    restart: unless-stopped
    ports:
      - "9000:9000"    # HTTP Interface
      - "9443:9443"    # HTTPS Interface
      - "8000:8000"    # Edge Agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    environment:
      # SSL-Zertifikat für HTTPS automatisch generieren
      - PORTAINER_ENABLE_HTTPS=true
    command: --admin-password-file /tmp/portainer_password
    configs:
      - source: portainer_password
        target: /tmp/portainer_password
    networks:
      - portainer_network

  # Watchtower für automatische Updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600  # Alle Stunde prüfen
      - WATCHTOWER_INCLUDE_STOPPED=true
    networks:
      - portainer_network

configs:
  portainer_password:
    # Standard Admin-Passwort: RebeleinTask2025!
    # Kann später über Interface geändert werden
    external: false
    file: ./portainer_password.txt

volumes:
  portainer_data:
    driver: local

networks:
  portainer_network:
    driver: bridge
